"""Initial migration

Revision ID: 9103d30b891b
Revises: 
Create Date: 2026-05-14 23:05:11.025088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9103d30b891b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('idx_user_name', ['first_name', 'last_name'], unique=False)
        batch_op.create_index('idx_user_role_active', ['role', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('teachers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('subject', sa.String(length=100), nullable=False),
    sa.Column('qualification', sa.String(length=200), nullable=True),
    sa.Column('date_joined', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teachers_employee_id'), ['employee_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_teachers_user_id'), ['user_id'], unique=True)

    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('class_teacher_id', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('room_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.create_index('idx_class_name_year', ['name', 'year'], unique=False)
        batch_op.create_index('idx_class_year_active', ['year', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_class_teacher_id'), ['class_teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_classes_name'), ['name'], unique=True)
        batch_op.create_index(batch_op.f('ix_classes_year'), ['year'], unique=False)

    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('admission_number', sa.String(length=20), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('guardian_name', sa.String(length=200), nullable=False),
    sa.Column('guardian_phone', sa.String(length=20), nullable=False),
    sa.Column('date_enrolled', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index('idx_student_admission', ['admission_number'], unique=False)
        batch_op.create_index('idx_student_class', ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_admission_number'), ['admission_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_students_class_id'), ['class_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_students_user_id'), ['user_id'], unique=True)

    op.create_table('teacher_classes',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ),
    sa.PrimaryKeyConstraint('teacher_id', 'class_id')
    )
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('marked_by_id', sa.Integer(), nullable=False),
    sa.Column('remarks', sa.String(length=200), nullable=True),
    sa.Column('check_in_time', sa.Time(), nullable=True),
    sa.Column('check_out_time', sa.Time(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['marked_by_id'], ['teachers.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'date', name='unique_student_attendance_per_day')
    )
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.create_index('idx_attendance_date_status', ['date', 'status'], unique=False)
        batch_op.create_index('idx_attendance_marked_by', ['marked_by_id', 'date'], unique=False)
        batch_op.create_index('idx_attendance_student_date', ['student_id', 'date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_marked_by_id'), ['marked_by_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendance_student_id'), ['student_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendance_student_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_status'))
        batch_op.drop_index(batch_op.f('ix_attendance_marked_by_id'))
        batch_op.drop_index(batch_op.f('ix_attendance_date'))
        batch_op.drop_index('idx_attendance_student_date')
        batch_op.drop_index('idx_attendance_marked_by')
        batch_op.drop_index('idx_attendance_date_status')

    op.drop_table('attendance')
    op.drop_table('teacher_classes')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_user_id'))
        batch_op.drop_index(batch_op.f('ix_students_gender'))
        batch_op.drop_index(batch_op.f('ix_students_class_id'))
        batch_op.drop_index(batch_op.f('ix_students_admission_number'))
        batch_op.drop_index('idx_student_class')
        batch_op.drop_index('idx_student_admission')

    op.drop_table('students')
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_year'))
        batch_op.drop_index(batch_op.f('ix_classes_name'))
        batch_op.drop_index(batch_op.f('ix_classes_is_active'))
        batch_op.drop_index(batch_op.f('ix_classes_class_teacher_id'))
        batch_op.drop_index('idx_class_year_active')
        batch_op.drop_index('idx_class_name_year')

    op.drop_table('classes')
    with op.batch_alter_table('teachers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teachers_user_id'))
        batch_op.drop_index(batch_op.f('ix_teachers_employee_id'))

    op.drop_table('teachers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_active'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index('idx_user_role_active')
        batch_op.drop_index('idx_user_name')

    op.drop_table('users')
    # ### end Alembic commands ###
